CREATE TABLE Billett
( id INTEGER AUTO_INCREMENT NOT NULL,
movie VARCHAR(255) NOT NULL,
quantity VARCHAR(255) NOT NULL,
firstname VARCHAR(255) NOT NULL,
surname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
phone VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);